//===- ConduitBinding.td -----------------------------------*- tablegen -*-===//
//
// Copyright (C) 2025, Advanced Micro Devices, Inc.
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef CONDUIT_BINDING_TD
#define CONDUIT_BINDING_TD

include "aie/Dialect/Conduit/IR/Conduit.td"

#endif // CONDUIT_BINDING_TD
